<a href="https://colab.research.google.com/github/Chaitanya-Kumaria/Deep-Learning-Notes/blob/main/SVD_For_Word_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import numpy as np
import pandas as pd
np.set_printoptions(linewidth=120)

In [17]:
# Corpus
sentences = ['Human machine interface for computer applications','User opinion of computer system response time','User interface management system','System engineering for improved response time']

In [18]:
# Vocabulary
vocab=list(set((" ".join(sentences)).split()))
vocab

['User',
 'system',
 'applications',
 'engineering',
 'improved',
 'computer',
 'machine',
 'time',
 'System',
 'of',
 'interface',
 'response',
 'Human',
 'for',
 'opinion',
 'management']

In [19]:
text_data=[]
for i in sentences:
    text_data.append(i.split())
text_data

[['Human', 'machine', 'interface', 'for', 'computer', 'applications'],
 ['User', 'opinion', 'of', 'computer', 'system', 'response', 'time'],
 ['User', 'interface', 'management', 'system'],
 ['System', 'engineering', 'for', 'improved', 'response', 'time']]

In [36]:
window_size = 1
w=[]
for i in sentences:
    i=i.split(' ') #if i is list
    for k in range(len(i)-window_size+1):
        for l in range(k+1,k+window_size+1):
            if l<=len(i)-1:
                w.append([i[k],i[l]])
w

[['Human', 'machine'],
 ['machine', 'interface'],
 ['interface', 'for'],
 ['for', 'computer'],
 ['computer', 'applications'],
 ['User', 'opinion'],
 ['opinion', 'of'],
 ['of', 'computer'],
 ['computer', 'system'],
 ['system', 'response'],
 ['response', 'time'],
 ['User', 'interface'],
 ['interface', 'management'],
 ['management', 'system'],
 ['System', 'engineering'],
 ['engineering', 'for'],
 ['for', 'improved'],
 ['improved', 'response'],
 ['response', 'time']]

In [37]:
w1=[x[::-1] for x in w]
w.extend(w1)

In [26]:
a=np.zeros((len(vocab),len(vocab)))
df=pd.DataFrame(a,index=vocab,columns=vocab)
for i in w:
    df.at[i[0],i[1]]+=1


In [27]:
# Co occurence matrix
df

User  system  applications  engineering  improved  computer  \
User           0.0     1.0           0.0          0.0       0.0       1.0   
system         1.0     0.0           0.0          0.0       0.0       1.0   
applications   0.0     0.0           0.0          0.0       0.0       0.0   
engineering    0.0     0.0           0.0          0.0       1.0       0.0   
improved       0.0     0.0           0.0          1.0       0.0       0.0   
computer       1.0     1.0           0.0          0.0       0.0       0.0   
machine        0.0     0.0           0.0          0.0       0.0       1.0   
time           0.0     1.0           0.0          0.0       1.0       1.0   
System         0.0     0.0           0.0          1.0       1.0       0.0   
of             1.0     1.0           0.0          0.0       0.0       1.0   
interface      1.0     1.0           1.0          0.0       0.0       1.0   
response       0.0     1.0           0.0          1.0       1.0       1.0   
Human          0.0     0.0           0.0          0.0       0.0       0.0   
for            0.0     0.0           1.0          1.0       1.0       1.0   
opinion        1.0     1.0           0.0          0.0       0.0       1.0   
management     1.0     0.0           0.0          0.0       0.0       0.0   

              machine  time  System   of  interface  response  Human  for  \
User              0.0   0.0     0.0  1.0        1.0       0.0    0.0  0.0   
system            0.0   1.0     0.0  1.0        1.0       1.0    0.0  0.0   
applications      0.0   0.0     0.0  0.0        1.0       0.0    0.0  1.0   
engineering       0.0   0.0     1.0  0.0        0.0       1.0    0.0  1.0   
improved          0.0   1.0     1.0  0.0        0.0       1.0    0.0  1.0   
computer          1.0   1.0     0.0  1.0        1.0       1.0    0.0  1.0   
machine           0.0   0.0     0.0  0.0        1.0       0.0    1.0  1.0   
time              0.0   0.0     0.0  0.0        0.0       0.0    0.0  1.0   
System            0.0   0.0     0.0  0.0        0.0       0.0    0.0  1.0   
of                0.0   0.0     0.0  0.0        0.0       1.0    0.0  0.0   
interface         1.0   0.0     0.0  0.0        0.0       0.0    1.0  1.0   
response          0.0   0.0     0.0  1.0        0.0       0.0    0.0  1.0   
Human             1.0   0.0     0.0  0.0        1.0       0.0    0.0  1.0   
for               1.0   1.0     1.0  0.0        1.0       1.0    1.0  0.0   
opinion           0.0   0.0     0.0  1.0        0.0       0.0    0.0  0.0   
management        0.0   0.0     0.0  0.0        1.0       0.0    0.0  0.0   

              opinion  management  
User              1.0         1.0  
system            1.0         0.0  
applications      0.0         0.0  
engineering       0.0         0.0  
improved          0.0         0.0  
computer          1.0         0.0  
machine           0.0         0.0  
time              0.0         0.0  
System            0.0         0.0  
of                1.0         0.0  
interface         0.0         1.0  
response          0.0         0.0  
Human             0.0         0.0  
for               0.0         0.0  
opinion           0.0         0.0  
management        0.0         0.0

In [28]:
from numpy import array
from scipy.linalg import svd
from numpy import diag
from numpy import dot
# define a matrix
A = array(df)
print('Matrix A is: \n')
print(A)
# SVD
U, s, VT = svd(A)
print('*'*120)
print('Matrix U is: \n')
print(U)
print('*'*120)
Sigma = diag(s)
print('Matrix Sigma is: \n')
print(Sigma)
print('*'*120)
print('Matrix VT is: \n')
print(VT)

Matrix A is: 

[[0. 1. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1.]
 [1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
************************************************************************************************************************
Matrix U is: 

[[-2.72906057e-01 -3.46991670e-0

In [29]:
U.shape,Sigma.shape,VT.shape


((16, 16), (16, 16), (16, 16))

In [30]:
k = 3
U=U[:,:k]
Sigma=Sigma[:k,:k]
VT=VT[:k,:]
U.shape,Sigma.shape,VT.shape

((16, 3), (3, 3), (3, 16))

In [31]:
U_df=pd.DataFrame(U,index=vocab)
U_df

0         1         2
User         -0.272906 -0.346992  0.112506
system       -0.330598 -0.271971 -0.400040
applications -0.115616  0.099459 -0.022855
engineering  -0.160902  0.353607 -0.034184
improved     -0.191969  0.375677 -0.247277
computer     -0.412916 -0.162715 -0.313573
machine      -0.209672  0.088561  0.102679
time         -0.217201  0.098140  0.416945
System       -0.119959  0.326851  0.187146
of           -0.252781 -0.281794 -0.013467
interface    -0.326848 -0.054462  0.339435
response     -0.286247  0.118975  0.433061
Human        -0.150611  0.125154 -0.057583
for          -0.365849  0.397266 -0.271861
opinion      -0.211838 -0.308550  0.207863
management   -0.100103 -0.116476 -0.152857

In [32]:
model={}
c=0
for i in list(U_df.index):
    model[i]=list(U_df.loc[i])
    c=c+1
model

{'User': [-0.2729060566757707, -0.34699166994188385, 0.11250597273584256],
 'system': [-0.3305978036144925, -0.2719714254699279, -0.4000396583467729],
 'applications': [-0.11561564121988899,
  0.09945909771484596,
  -0.022855153372538746],
 'engineering': [-0.1609018011377786,
  0.3536070607510956,
  -0.034183914628819013],
 'improved': [-0.1919687358003676, 0.37567744368990097, -0.2472770214995913],
 'computer': [-0.41291648329236286, -0.16271525077156732, -0.3135733959750075],
 'machine': [-0.20967206369158475, 0.08856121436511899, 0.10267853073593675],
 'time': [-0.21720073851934035, 0.09813988441868225, 0.4169445586091792],
 'System': [-0.11995894979553394, 0.3268510538785066, 0.1871461287559145],
 'of': [-0.2527807085329167, -0.2817939392709829, -0.013467054732051377],
 'interface': [-0.32684812580267936,
  -0.054462329216796154,
  0.3394353447646381],
 'response': [-0.2862470226047724, 0.11897534488921377, 0.43306120315736923],
 'Human': [-0.1506112635534321, 0.12515375689544866,